### PR TITLE
More brainstorming

### PR DESCRIPTION
**Pull request by joaquimg**

### CODE REVIEW

**Comment by odow** [comment]
I made some changes. Please re-re-edit if you want.

**Comment by odow** [comment]
Why is this on your fork? Don't you have commit access?

**Comment by joaquimg** [comment]
> Why is this on your fork? Don't you have commit access?

did not try, my bad

**Comment by joaquimg** [comment]
> I made some changes. Please re-re-edit if you want.

minor fixes and its good to go, for me

**Comment by joaquimg** [comment]
kind of a side question, should we define problem, policy and algorithm?

**Comment by odow** [comment]
> kind of a side question, should we define problem, policy and algorithm?

Yes. Somewhere. But I haven't got to that yet...

**Pull request merged**
